import "oaidl.idl";
import "ocidl.idl";

[
	oleautomation,
	object,
	uuid(2715DB2C-616E-4C8D-BC30-386E87F2083E),
	pointer_default(unique)
]
interface ICallbackClient : IUnknown
{
	HRESULT Callback();
};

[
	oleautomation,
	object,
	uuid(621b055e-d513-48cf-8a36-12b41d8fb004),
	pointer_default(unique)
]
interface IComServer : IUnknown
{
    HRESULT LongRunningTask([in] ICallbackClient* slave);
};

[
	uuid(6ed1b1aa-807b-4a28-87b6-fcdc18ab8dc3),
	version(1.0),
]
library ComServerLib
{
	interface IComServer;
	interface ICallbackClient;

	[
		uuid(3254171b-5d49-4ec9-874a-e3c065c1b801),
	]
	coclass ComServer
	{
		[default] interface IComServer;
	};

	[
		uuid(609F7F2C-67A8-4D4C-A889-38232048AF1C),
	]
	coclass CallbackClient
	{
		[default] interface ICallbackClient;
	};
};

