import "oaidl.idl";
import "ocidl.idl";

[
	oleautomation,
	object,
	uuid(621b055e-d513-48cf-8a36-12b41d8fb004),
	pointer_default(unique)
]
interface IComServer : IUnknown
{
    HRESULT LongRunningTask([in] IComServer* slave);
    HRESULT Callback();
};

[
	uuid(6ed1b1aa-807b-4a28-87b6-fcdc18ab8dc3),
	version(1.0),
]
library ComServerLib
{
	interface IComServer;

	importlib("stdole2.tlb");
	[
		uuid(3254171b-5d49-4ec9-874a-e3c065c1b801),
	]
	coclass ComServer
	{
		[default] interface IComServer;
	};
};

